import { createRoute, z } from '@hono/zod-openapi';
import { and, desc, eq, inArray, isNotNull, isNull, lt, or, sql } from 'drizzle-orm';
import { Buffer } from 'node:buffer';
import { actor, ApiError, errors, id, IdParams, json, notFound, PageQuery, page, response, security, type Actor, type App, type DbExecutor, type Runtime } from './core.js';
import { attachmentLinks, attachments } from './db/sending.js';
import { templateAssetLinks, templateAssets, templates, type TemplateDraft } from './db/templates.js';
import { BlockContentError, renderBlockHtml, renderBlockText, validateBlockHtml } from './campaign-blocks.js';

const MAX_ASSET_BYTES = 8 * 1024 * 1024;
const Scalar = z.union([z.string().max(65536), z.number().finite(), z.boolean(), z.null()]);
const Data = z.record(z.string().max(120), Scalar).default({}).describe('Fallback values for simple {{name}} placeholders. OpenSend HTML-escapes substituted values. Call getContentGuide in MCP before writing personalized content.');
const Address = z.string().email().max(254).regex(/^[\x21-\x7e]+$/);
const BlockHtml = z.string().max(512 * 1024).describe('OpenSend block HTML shared with the campaign editor. Call getContentGuide in MCP before writing: arbitrary document HTML, CSS, tables and scripts are rejected.').optional();
const AssetIds = z.array(z.string().regex(/^tasset_[0-9a-f]{32}$/)).max(20).default([]);
const DraftFields = { name: z.string().trim().min(1).max(200), description: z.string().trim().max(500).default(''), subject: z.string().max(998).refine(value => !/[\r\n]/.test(value), 'Subject cannot contain line breaks.').default(''), previewText: z.string().max(200).optional(), fromName: z.string().max(200).optional(), replyTo: z.array(Address).max(10).default([]), tracking: z.boolean().default(true), defaults: Data, html: BlockHtml, attachments: AssetIds };
const TemplateDraftSchema = z.object(DraftFields).strict().openapi('CampaignTemplateDraft');
const Template = z.object({ id: z.string(), url: z.string().url(), revision: z.number().int(), draft: TemplateDraftSchema, published: z.union([TemplateDraftSchema, z.null()]), publishedRevision: z.number().int().nullable(), archivedAt: z.string().nullable(), createdAt: z.string(), updatedAt: z.string() }).openapi('CampaignTemplate');
const TemplateSummary = Template.omit({ draft: true, published: true }).extend({ name: z.string(), description: z.string(), subject: z.string(), published: z.boolean() }).openapi('CampaignTemplateSummary');
const TemplateCreate = z.object({ name: DraftFields.name, description: DraftFields.description.optional() }).strict().openapi('CreateCampaignTemplate');
const TemplateUpdate = z.object({ revision: z.number().int().positive(), draft: TemplateDraftSchema }).strict().openapi('UpdateCampaignTemplate');
const TemplateRevision = z.object({ revision: z.number().int().positive() }).strict();
const TemplateArchive = z.object({ archived: z.boolean() }).strict();
const TemplatePreview = z.object({ html: z.string(), text: z.string(), revision: z.number().int(), published: z.boolean() }).openapi('CampaignTemplatePreview');
const AssetMetadata = z.object({ filename: z.string().min(1).max(200).regex(/^[^\x00-\x1f\x7f/\\]+$/), contentType: z.string().max(100).regex(/^[a-zA-Z0-9!#$&^_.+-]+\/[a-zA-Z0-9!#$&^_.+-]+$/).default('application/octet-stream'), disposition: z.enum(['attachment', 'inline']).default('attachment'), contentId: z.string().min(1).max(120).regex(/^[a-zA-Z0-9_.@-]+$/).optional() }).strict();
const AssetInput = AssetMetadata.extend({ content: z.string().min(4).max(Math.ceil(MAX_ASSET_BYTES / 3) * 4) }).strict().openapi('TemplateAssetUpload');
const Asset = z.object({ id: z.string(), filename: z.string(), contentType: z.string(), size: z.number().int(), disposition: z.enum(['attachment', 'inline']), contentId: z.string().nullable(), createdAt: z.string() }).openapi('TemplateAsset');
const ImageImport = z.object({ url: z.string().url().max(2048), filename: AssetMetadata.shape.filename.optional(), contentId: AssetMetadata.shape.contentId }).strict().openapi('TemplateImageImport');
const ImportedImage = z.object({ asset: Asset, src: z.string().regex(/^cid:/) }).openapi('ImportedTemplateImage');
const TemplatePreviewImage = z.object({ data: z.string().describe('Canonical base64 PNG screenshot.'), mimeType: z.literal('image/png'), revision: z.number().int(), published: z.boolean() }).openapi('CampaignTemplatePreviewImage');
const Removed = z.object({ id: z.string(), deleted: z.literal(true) });
const Query = PageQuery.extend({ search: z.string().trim().min(1).max(200).optional(), archived: z.enum(['true', 'false']).default('false'), publishedOnly: z.enum(['true', 'false']).default('false') });

const starts = (bytes: Uint8Array, prefix: number[]) => prefix.every((value, index) => bytes[index] === value);
function validateAsset(metadata: z.infer<typeof AssetMetadata>, bytes: Uint8Array) {
  const extension = metadata.filename.split('.').pop()?.toLowerCase();
  const types: Record<string, string> = { pdf: 'application/pdf', txt: 'text/plain', csv: 'text/csv', json: 'application/json', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp', ics: 'text/calendar' };
  const expected = extension ? types[extension] : undefined; if (!expected) throw new ApiError(422, 'UNSUPPORTED_TEMPLATE_ASSET', 'Template assets allow PDF, UTF-8 text, CSV, JSON, PNG, JPEG, GIF, WebP, and ICS files.');
  const declared = metadata.contentType.split(';')[0]!.toLowerCase(); if (declared !== 'application/octet-stream' && declared !== expected) throw new ApiError(422, 'TEMPLATE_ASSET_TYPE_MISMATCH', 'The template asset content type does not match its filename.');
  if (metadata.disposition === 'inline' && (!['png', 'jpg', 'jpeg', 'gif', 'webp'].includes(extension!) || !metadata.contentId)) throw new ApiError(422, 'INLINE_TEMPLATE_ASSET_INVALID', 'Only raster images with a content ID may be inline.');
  if (metadata.disposition === 'attachment' && metadata.contentId) throw new ApiError(422, 'TEMPLATE_ASSET_CONTENT_ID_INVALID', 'Content IDs are only supported for inline images.');
  const ascii = (start: number, end: number) => new TextDecoder('latin1').decode(bytes.slice(start, end));
  let valid = true;
  if (extension === 'png') valid = starts(bytes, [0x89, 0x50, 0x4e, 0x47, 13, 10, 26, 10]);
  else if (extension === 'jpg' || extension === 'jpeg') valid = starts(bytes, [0xff, 0xd8, 0xff]);
  else if (extension === 'gif') valid = ['GIF87a', 'GIF89a'].includes(ascii(0, 6));
  else if (extension === 'webp') valid = ascii(0, 4) === 'RIFF' && ascii(8, 12) === 'WEBP';
  else if (extension === 'pdf') valid = ascii(0, 5) === '%PDF-';
  else { try { const text = new TextDecoder('utf-8', { fatal: true }).decode(bytes); valid = !text.includes('\0') && (extension !== 'json' || Boolean(JSON.parse(text))) && (extension !== 'ics' || text.replaceAll('\r\n', '\n').trim().startsWith('BEGIN:VCALENDAR\n') && text.replaceAll('\r\n', '\n').trim().endsWith('END:VCALENDAR')); } catch { valid = false; } }
  if (!valid) throw new ApiError(422, 'TEMPLATE_ASSET_INVALID', 'The template asset bytes do not match its filename.');
  return { ...metadata, contentType: declared === 'application/octet-stream' ? expected : metadata.contentType };
}
function assertContent(html?: string, complete = false) { if (!html) return; try { validateBlockHtml(html, { complete }); } catch (error) { if (error instanceof BlockContentError) throw new ApiError(422, 'TEMPLATE_CONTENT_INVALID', error.message, 'html'); throw error; } }
function templateUrl(runtime: Runtime, templateId: string) { return new URL(`/templates/${encodeURIComponent(templateId)}`, runtime.config.publicUrl).href; }
function view(runtime: Runtime, row: typeof templates.$inferSelect) { return Template.parse({ ...row, published: row.published ?? null, publishedRevision: row.publishedRevision ?? null, archivedAt: row.archivedAt ?? null, url: templateUrl(runtime, row.id) }); }
function summary(runtime: Runtime, row: typeof templates.$inferSelect) { return TemplateSummary.parse({ id: row.id, url: templateUrl(runtime, row.id), revision: row.revision, publishedRevision: row.publishedRevision ?? null, archivedAt: row.archivedAt ?? null, createdAt: row.createdAt, updatedAt: row.updatedAt, name: row.draft.name, description: row.draft.description, subject: row.draft.subject, published: !!row.published }); }
async function findTemplate(db: DbExecutor, workspaceId: string, templateId: string, lock = false) { const query = db.select().from(templates).where(and(eq(templates.workspaceId, workspaceId), eq(templates.id, templateId))).limit(1); const [row] = lock ? await query.for('update') : await query; return row ?? notFound('Template'); }
async function assetRows(db: DbExecutor, workspaceId: string, ids: string[]) { const unique = [...new Set(ids)]; if (unique.length !== ids.length) throw new ApiError(422, 'DUPLICATE_TEMPLATE_ASSET', 'Template asset IDs must be unique.'); const rows = unique.length ? await db.select().from(templateAssets).where(and(eq(templateAssets.workspaceId, workspaceId), inArray(templateAssets.id, unique))) : []; if (rows.length !== unique.length) throw new ApiError(422, 'TEMPLATE_ASSET_NOT_FOUND', 'A template asset was not found.'); if (rows.reduce((sum, row) => sum + row.size, 0) > MAX_ASSET_BYTES) throw new ApiError(413, 'TEMPLATE_ASSETS_TOO_LARGE', 'Template assets may total at most 8 MiB.'); return unique.map(value => rows.find(row => row.id === value)!); }
async function replaceLinks(db: DbExecutor, workspaceId: string, templateId: string, stage: 'draft' | 'published', ids: string[]) { await assetRows(db, workspaceId, ids); await db.delete(templateAssetLinks).where(and(eq(templateAssetLinks.workspaceId, workspaceId), eq(templateAssetLinks.templateId, templateId), eq(templateAssetLinks.stage, stage))); if (ids.length) await db.insert(templateAssetLinks).values(ids.map(assetId => ({ workspaceId, templateId, assetId, stage }))); }
async function checksum(bytes: Uint8Array) { return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes as Uint8Array<ArrayBuffer>)), byte => byte.toString(16).padStart(2, '0')).join(''); }
async function saveAsset(runtime: Runtime, identity: Actor, metadata: z.infer<typeof AssetMetadata>, bytes: Uint8Array) {
  if (!bytes.length || bytes.length > MAX_ASSET_BYTES) throw new ApiError(413, 'TEMPLATE_ASSET_LIMIT_EXCEEDED', 'Template assets must be between 1 byte and 8 MiB.');
  const input = validateAsset(metadata, bytes), assetId = id('tasset'), storageKey = `${identity.workspaceId}/templates/assets/${assetId}`, hash = await checksum(bytes);
  await runtime.storage.put(storageKey, bytes, input.contentType);
  try { const [row] = await runtime.db.insert(templateAssets).values({ id: assetId, workspaceId: identity.workspaceId, ...input, contentId: input.contentId ?? null, size: bytes.length, storageKey, checksum: hash }).returning(); return Asset.parse(row); }
  catch (error) { await runtime.storage.delete(storageKey).catch(() => undefined); throw error; }
}
function readTemplateCursor(value?: string) {
  if (!value) return null;
  try { const parsed = z.tuple([z.string(), z.string().min(1).max(120)]).parse(JSON.parse(Buffer.from(value, 'base64url').toString('utf8'))); return { at: parsed[0], id: parsed[1] }; }
  catch { throw new ApiError(422, 'INVALID_CURSOR', 'Use the returned template cursor with the same filters.', 'cursor'); }
}
function templateCursor(rows: (typeof templates.$inferSelect)[], limit: number) { const last = rows[limit - 1]; return rows.length > limit && last ? Buffer.from(JSON.stringify([last.updatedAt, last.id])).toString('base64url') : null; }

export async function instantiateTemplate(runtime: Runtime, db: DbExecutor, identity: Actor, templateId: string) {
  const template = await findTemplate(db, identity.workspaceId, templateId, true);
  if (template.archivedAt || !template.published || !template.publishedRevision) throw new ApiError(409, 'TEMPLATE_NOT_AVAILABLE', 'Choose a published, active template.');
  const source = await assetRows(db, identity.workspaceId, template.published.attachments);
  const cloned = source.map(asset => ({ id: id('attachment'), workspaceId: identity.workspaceId, environment: identity.environment, filename: asset.filename, contentType: asset.contentType, size: asset.size, disposition: asset.disposition, contentId: asset.contentId, storageKey: asset.storageKey, checksum: asset.checksum, sourceTemplateAssetId: asset.id }));
  if (cloned.length) await db.insert(attachments).values(cloned);
  return { draft: { ...template.published, attachments: cloned.map(asset => asset.id) }, templateId: template.id, templateRevision: template.publishedRevision };
}

export function registerTemplates(app: App) {
  app.openapi(createRoute({ method: 'get', path: '/v1/templates', operationId: 'listCampaignTemplates', tags: ['Templates'], security, request: { query: Query }, responses: { 200: response(page(TemplateSummary)), ...errors } }), async c => { const identity = actor(c), query = c.req.valid('query'), cursor = readTemplateCursor(query.cursor), search = query.search ? `%${query.search.replaceAll('%', '\\%').replaceAll('_', '\\_')}%` : undefined; const rows = await c.env.db.select().from(templates).where(and(eq(templates.workspaceId, identity.workspaceId), query.archived === 'true' ? isNotNull(templates.archivedAt) : isNull(templates.archivedAt), query.publishedOnly === 'true' ? isNotNull(templates.published) : undefined, cursor ? or(lt(templates.updatedAt, cursor.at), and(eq(templates.updatedAt, cursor.at), lt(templates.id, cursor.id))) : undefined, search ? or(sql`${templates.draft}->>'name' ILIKE ${search}`, sql`${templates.draft}->>'description' ILIKE ${search}`) : undefined)).orderBy(desc(templates.updatedAt), desc(templates.id)).limit(query.limit + 1); return c.json({ data: rows.slice(0, query.limit).map(row => summary(c.env, row)), nextCursor: templateCursor(rows, query.limit) }, 200); });
  app.openapi(createRoute({ method: 'post', path: '/v1/templates', operationId: 'createCampaignTemplate', tags: ['Templates'], security, request: { body: json(TemplateCreate) }, responses: { 201: response(Template), ...errors } }), async c => { const identity = actor(c, 'manage'), input = c.req.valid('json'); const [row] = await c.env.db.insert(templates).values({ id: id('tpl'), workspaceId: identity.workspaceId, draft: TemplateDraftSchema.parse({ name: input.name, description: input.description ?? '' }) }).returning(); return c.json(view(c.env, row!), 201); });
  app.openapi(createRoute({ method: 'get', path: '/v1/templates/{id}', operationId: 'getCampaignTemplate', tags: ['Templates'], security, request: { params: IdParams }, responses: { 200: response(Template), ...errors } }), async c => c.json(view(c.env, await findTemplate(c.env.db, actor(c).workspaceId, c.req.valid('param').id)), 200));
  app.openapi(createRoute({ method: 'patch', path: '/v1/templates/{id}', operationId: 'updateCampaignTemplate', tags: ['Templates'], security, request: { params: IdParams, body: json(TemplateUpdate) }, responses: { 200: response(Template), ...errors } }), async c => { const identity = actor(c, 'manage'), input = c.req.valid('json'); assertContent(input.draft.html); const row = await c.env.db.transaction(async db => { const current = await findTemplate(db, identity.workspaceId, c.req.valid('param').id, true); if (current.archivedAt) throw new ApiError(409, 'TEMPLATE_ARCHIVED', 'Restore this template before editing.'); if (current.revision !== input.revision) throw new ApiError(409, 'STALE_TEMPLATE_REVISION', 'The template changed. Load the latest revision before saving.'); await replaceLinks(db, identity.workspaceId, current.id, 'draft', input.draft.attachments); const [updated] = await db.update(templates).set({ draft: input.draft, revision: current.revision + 1, updatedAt: new Date().toISOString() }).where(and(eq(templates.workspaceId, identity.workspaceId), eq(templates.id, current.id))).returning(); return updated!; }); return c.json(view(c.env, row), 200); });
  app.openapi(createRoute({ method: 'post', path: '/v1/templates/{id}/publish', operationId: 'publishCampaignTemplate', tags: ['Templates'], security, request: { params: IdParams, body: json(TemplateRevision) }, responses: { 200: response(Template), ...errors } }), async c => { const identity = actor(c, 'manage'), revision = c.req.valid('json').revision; const row = await c.env.db.transaction(async db => { const current = await findTemplate(db, identity.workspaceId, c.req.valid('param').id, true); if (current.archivedAt) throw new ApiError(409, 'TEMPLATE_ARCHIVED', 'Restore this template before publishing.'); if (current.revision !== revision) throw new ApiError(409, 'STALE_TEMPLATE_REVISION', 'The template changed. Load the latest revision before publishing.'); assertContent(current.draft.html, true); await replaceLinks(db, identity.workspaceId, current.id, 'published', current.draft.attachments); const [updated] = await db.update(templates).set({ published: current.draft, publishedRevision: current.revision, updatedAt: new Date().toISOString() }).where(and(eq(templates.workspaceId, identity.workspaceId), eq(templates.id, current.id))).returning(); return updated!; }); return c.json(view(c.env, row), 200); });
  app.openapi(createRoute({ method: 'get', path: '/v1/templates/{id}/preview', operationId: 'previewCampaignTemplate', tags: ['Templates'], security, request: { params: IdParams, query: z.object({ published: z.enum(['true', 'false']).default('false') }) }, responses: { 200: response(TemplatePreview), ...errors } }), async c => { const identity = actor(c), row = await findTemplate(c.env.db, identity.workspaceId, c.req.valid('param').id), published = c.req.valid('query').published === 'true', draft = published ? row.published : row.draft; if (!draft) throw new ApiError(404, 'NOT_FOUND', 'This template has no published revision.'); assertContent(draft.html); const html = draft.html ? renderBlockHtml(draft.html, { fontBase: `${c.env.config.publicUrl}/fonts/`, title: draft.subject }) : ''; return c.json({ html, text: draft.html ? renderBlockText(draft.html) : '', revision: published ? row.publishedRevision! : row.revision, published }, 200); });
  app.openapi(createRoute({ method: 'get', path: '/v1/templates/{id}/preview-image', operationId: 'renderCampaignTemplatePreviewImage', description: 'Renders a template draft or published revision as a full-page PNG. Inline template assets are embedded, so agents can verify the result without browser automation.', tags: ['Templates'], security, request: { params: IdParams, query: z.object({ published: z.enum(['true', 'false']).default('false') }) }, responses: { 200: response(TemplatePreviewImage), ...errors } }), async c => {
    const identity = actor(c), row = await findTemplate(c.env.db, identity.workspaceId, c.req.valid('param').id), published = c.req.valid('query').published === 'true', draft = published ? row.published : row.draft;
    if (!draft) throw new ApiError(404, 'NOT_FOUND', 'This template has no published revision.');
    if (!c.env.renderHtmlImage) throw new ApiError(503, 'PREVIEW_RENDERING_UNAVAILABLE', 'Visual template preview rendering is not configured.', undefined, true);
    assertContent(draft.html); let html = draft.html ? renderBlockHtml(draft.html, { fontBase: `${c.env.config.publicUrl}/fonts/`, title: draft.subject }) : '';
    for (const item of (await assetRows(c.env.db, identity.workspaceId, draft.attachments)).filter(asset => asset.disposition === 'inline' && asset.contentId)) {
      const stored = await c.env.storage.get(item.storageKey);
      if (!stored || stored.body.length !== item.size || await checksum(stored.body) !== item.checksum) throw new ApiError(503, 'TEMPLATE_ASSET_STORAGE_UNAVAILABLE', 'An inline template image is missing or changed.', undefined, true);
      html = html.replaceAll(`cid:${item.contentId}`, `data:${item.contentType};base64,${Buffer.from(stored.body).toString('base64')}`);
    }
    try { const image = await c.env.renderHtmlImage(html); return c.json({ data: Buffer.from(image.data).toString('base64'), mimeType: image.mimeType, revision: published ? row.publishedRevision! : row.revision, published }, 200); }
    catch (error) { if (error instanceof ApiError) throw error; throw new ApiError(503, 'PREVIEW_RENDERING_FAILED', 'The visual template preview could not be rendered. Try again.', undefined, true); }
  });
  app.openapi(createRoute({ method: 'patch', path: '/v1/templates/{id}/archive', operationId: 'setCampaignTemplateArchived', tags: ['Templates'], security, request: { params: IdParams, body: json(TemplateArchive) }, responses: { 200: response(Template), ...errors } }), async c => { const identity = actor(c, 'manage'), archived = c.req.valid('json').archived; const [row] = await c.env.db.update(templates).set({ archivedAt: archived ? new Date().toISOString() : null, updatedAt: new Date().toISOString() }).where(and(eq(templates.workspaceId, identity.workspaceId), eq(templates.id, c.req.valid('param').id))).returning(); return c.json(view(c.env, row ?? notFound('Template')), 200); });
  app.openapi(createRoute({ method: 'delete', path: '/v1/templates/{id}', operationId: 'deleteCampaignTemplate', tags: ['Templates'], security, request: { params: IdParams }, responses: { 200: response(Removed), ...errors } }), async c => { const identity = actor(c, 'manage'), templateId = c.req.valid('param').id; await c.env.db.transaction(async db => { const current = await findTemplate(db, identity.workspaceId, templateId, true); await db.delete(templateAssetLinks).where(and(eq(templateAssetLinks.workspaceId, identity.workspaceId), eq(templateAssetLinks.templateId, current.id))); await db.delete(templates).where(and(eq(templates.workspaceId, identity.workspaceId), eq(templates.id, current.id))); }); return c.json({ id: templateId, deleted: true as const }, 200); });
  app.openapi(createRoute({ method: 'post', path: '/v1/template-assets', operationId: 'uploadTemplateAsset', tags: ['Templates'], security, request: { body: json(AssetInput) }, responses: { 201: response(Asset), ...errors } }), async c => { const identity = actor(c, 'manage'), input = c.req.valid('json'); let bytes: Uint8Array; try { if (input.content.length % 4 || !/^[A-Za-z0-9+/]+={0,2}$/.test(input.content)) throw new Error(); bytes = new Uint8Array(Buffer.from(input.content, 'base64')); } catch { throw new ApiError(422, 'INVALID_BASE64', 'Template asset content must be canonical padded base64.'); } if (Buffer.from(bytes).toString('base64') !== input.content) throw new ApiError(422, 'INVALID_BASE64', 'Template asset content must be canonical padded base64.'); return c.json(await saveAsset(c.env, identity, input, bytes), 201); });
  app.openapi(createRoute({ method: 'post', path: '/v1/template-assets/import', operationId: 'importTemplateImage', description: 'Downloads a public HTTPS PNG, JPEG, GIF or WebP into private global template assets. Add asset.id to draft.attachments and use src in an img block. This is preferred over hotlinking and requires no browser automation or base64 in model context.', tags: ['Templates'], security, request: { body: json(ImageImport) }, responses: { 201: response(ImportedImage), ...errors } }), async c => {
    const identity = actor(c, 'manage'), input = c.req.valid('json');
    if (!c.env.importPublicImage) throw new ApiError(503, 'PUBLIC_IMAGE_IMPORT_UNAVAILABLE', 'Public image importing is not configured for this installation.', undefined, true);
    const imported = await c.env.importPublicImage(input.url), hash = await checksum(imported.data), extension = { 'image/png': 'png', 'image/jpeg': 'jpg', 'image/gif': 'gif', 'image/webp': 'webp' }[imported.contentType];
    const contentId = input.contentId ?? `image-${hash.slice(0, 16)}`;
    const asset = await saveAsset(c.env, identity, { filename: input.filename ?? `image-${hash.slice(0, 12)}.${extension}`, contentType: imported.contentType, disposition: 'inline', contentId }, imported.data);
    return c.json({ asset, src: `cid:${contentId}` }, 201);
  });
  app.openapi(createRoute({ method: 'get', path: '/v1/template-assets/{id}', operationId: 'getTemplateAsset', tags: ['Templates'], security, request: { params: IdParams }, responses: { 200: response(Asset), ...errors } }), async c => { const identity = actor(c), [row] = await c.env.db.select().from(templateAssets).where(and(eq(templateAssets.workspaceId, identity.workspaceId), eq(templateAssets.id, c.req.valid('param').id))).limit(1); return c.json(Asset.parse(row ?? notFound('Template asset')), 200); });
  app.openapi(createRoute({ method: 'get', path: '/v1/template-assets/{id}/content', operationId: 'getTemplateAssetContent', tags: ['Templates'], security, request: { params: IdParams }, responses: { 200: response(Asset.extend({ content: z.string() })), ...errors } }), async c => { const identity = actor(c), [row] = await c.env.db.select().from(templateAssets).where(and(eq(templateAssets.workspaceId, identity.workspaceId), eq(templateAssets.id, c.req.valid('param').id))).limit(1); if (!row) notFound('Template asset'); const stored = await c.env.storage.get(row!.storageKey); if (!stored || stored.body.length !== row!.size || await checksum(stored.body) !== row!.checksum) throw new ApiError(503, 'TEMPLATE_ASSET_STORAGE_UNAVAILABLE', 'A template asset is missing or changed.', undefined, true); return c.json({ ...Asset.parse(row), content: Buffer.from(stored.body).toString('base64') }, 200); });
  app.openapi(createRoute({ method: 'delete', path: '/v1/template-assets/{id}', operationId: 'deleteTemplateAsset', tags: ['Templates'], security, request: { params: IdParams }, responses: { 200: response(Removed), ...errors } }), async c => { const identity = actor(c, 'manage'), assetId = c.req.valid('param').id; await c.env.db.transaction(async db => { const [row] = await db.select().from(templateAssets).where(and(eq(templateAssets.workspaceId, identity.workspaceId), eq(templateAssets.id, assetId))).limit(1).for('update'); if (!row) notFound('Template asset'); const linked = await db.select({ id: templateAssetLinks.assetId }).from(templateAssetLinks).where(and(eq(templateAssetLinks.workspaceId, identity.workspaceId), eq(templateAssetLinks.assetId, assetId))).limit(1); const cloned = await db.select({ id: attachments.id }).from(attachments).where(and(eq(attachments.workspaceId, identity.workspaceId), eq(attachments.sourceTemplateAssetId, assetId))).limit(1); if (linked.length || cloned.length) throw new ApiError(409, 'TEMPLATE_ASSET_IN_USE', 'Remove this asset from template drafts, published revisions, and retained campaigns first.'); await c.env.storage.delete(row!.storageKey); await db.delete(templateAssets).where(and(eq(templateAssets.workspaceId, identity.workspaceId), eq(templateAssets.id, assetId))); }); return c.json({ id: assetId, deleted: true as const }, 200); });
}
