import { boolean, index, integer, jsonb, pgTable, primaryKey, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';
import type { Mode } from '../core.js';
export const eventTypes = ['email.sent', 'email.delivered', 'email.bounced', 'email.complained', 'email.rejected', 'email.rendering_failed', 'email.delivery_delayed', 'email.opened', 'email.clicked', 'contact.subscription_changed'] as const;
export type EventType = typeof eventTypes[number];
export interface PublishedEvent { id: string; type: EventType; createdAt: string; workspaceId: string; environment: Mode; region: string | null; data: { emailId?: string; [key: string]: unknown }; }
const scope = () => ({ workspaceId: text('workspace_id').notNull(), environment: text('environment').$type<Mode>().notNull() });
const dates = () => ({ createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow() });
export const workspaceSettings = pgTable('operation_settings', { ...scope(), name: text('name').notNull(), ...dates() }, t => [primaryKey({ columns: [t.workspaceId, t.environment] })]);
export const domains = pgTable('operation_domains', { id: text('id').primaryKey(), ...scope(), name: text('name').notNull(), region: text('region').notNull(), ...dates() }, t => [uniqueIndex('operation_domain_scope').on(t.workspaceId, t.environment, t.name, t.region)]);
export const webhooks = pgTable('operation_webhooks', { id: text('id').primaryKey(), ...scope(), url: text('url').notNull(), description: text('description').notNull().default(''), eventTypes: jsonb('event_types').$type<EventType[]>().notNull(), regions: jsonb('regions').$type<string[] | null>(), paused: boolean('paused').notNull().default(false), encryptedSecret: text('encrypted_secret').notNull(), ...dates() }, t => [index('operation_webhook_scope').on(t.workspaceId, t.environment, t.id)]);
export const events = pgTable('operation_events', { id: text('id').notNull(), ...scope(), type: text('type').$type<EventType>().notNull(), region: text('region'), data: jsonb('data').$type<PublishedEvent['data']>().notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull() }, t => [primaryKey({ columns: [t.workspaceId, t.environment, t.id] }), index('operation_events_metrics').on(t.workspaceId, t.environment, t.createdAt)]);
export const deliveries = pgTable('operation_deliveries', { id: text('id').primaryKey(), ...scope(), webhookId: text('webhook_id').notNull(), eventId: text('event_id').notNull(), payload: jsonb('payload').$type<PublishedEvent>().notNull(), synthetic: boolean('synthetic').notNull().default(false), status: text('status').$type<'pending' | 'delivered' | 'failed' | 'paused'>().notNull().default('pending'), attemptCount: integer('attempt_count').notNull().default(0), generation: integer('generation').notNull().default(0), lastStatusCode: integer('last_status_code'), lastError: text('last_error'), ...dates() }, t => [index('operation_delivery_scope').on(t.workspaceId, t.environment, t.webhookId, t.id), uniqueIndex('operation_delivery_event').on(t.workspaceId, t.environment, t.webhookId, t.eventId)]);
export const deliveryAttempts = pgTable('operation_delivery_attempts', { id: text('id').primaryKey(), ...scope(), deliveryId: text('delivery_id').notNull(), statusCode: integer('status_code'), error: text('error'), durationMs: integer('duration_ms').notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow() }, t => [index('operation_attempt_delivery').on(t.workspaceId, t.environment, t.deliveryId)]);
export const snsReceipts = pgTable('operation_sns_receipts', { topicArn: text('topic_arn').notNull(), messageId: text('message_id').notNull(), ...scope(), processedAt: timestamp('processed_at', { withTimezone: true, mode: 'string' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow() }, t => [primaryKey({ columns: [t.topicArn, t.messageId] })]);
export const unsubscribeTokens = pgTable('operation_unsubscribe_tokens', { tokenHash: text('token_hash').primaryKey(), ...scope(), email: text('email').notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow() });
