/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false` (hash: b7a60ad78b8deeb695ad07e8fcd195b7)
interface __BaseEnv_Env {
	ATTACHMENTS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	WAKE_QUEUE: Queue;
	ADMISSION: RateLimit;
	BROWSER: BrowserRun;
	PUBLIC_URL: "https://opensend.anoma.ly";
	DEFAULT_SES_REGION: "us-east-2";
	ENABLE_LIVE_SES: "true";
	JOB_CONCURRENCY: "4";
	WEBHOOK_ALLOWED_HOSTS: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_URL" | "DEFAULT_SES_REGION" | "ENABLE_LIVE_SES" | "JOB_CONCURRENCY" | "WEBHOOK_ALLOWED_HOSTS">> {}
}
